/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Step6CompleteRouteImport } from './routes/step-6/complete'
import { Route as Step5InstallationRouteImport } from './routes/step-5/installation'
import { Route as Step4PreparationRouteImport } from './routes/step-4/preparation'
import { Route as Step3SafetyChecklistRouteImport } from './routes/step-3/safety-checklist'
import { Route as Step2ModelDetailsRouteImport } from './routes/step-2/model-details'
import { Route as Step1IdentifyApplianceRouteImport } from './routes/step-1/identify-appliance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Step6CompleteRoute = Step6CompleteRouteImport.update({
  id: '/step-6/complete',
  path: '/step-6/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const Step5InstallationRoute = Step5InstallationRouteImport.update({
  id: '/step-5/installation',
  path: '/step-5/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const Step4PreparationRoute = Step4PreparationRouteImport.update({
  id: '/step-4/preparation',
  path: '/step-4/preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const Step3SafetyChecklistRoute = Step3SafetyChecklistRouteImport.update({
  id: '/step-3/safety-checklist',
  path: '/step-3/safety-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const Step2ModelDetailsRoute = Step2ModelDetailsRouteImport.update({
  id: '/step-2/model-details',
  path: '/step-2/model-details',
  getParentRoute: () => rootRouteImport,
} as any)
const Step1IdentifyApplianceRoute = Step1IdentifyApplianceRouteImport.update({
  id: '/step-1/identify-appliance',
  path: '/step-1/identify-appliance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/step-1/identify-appliance': typeof Step1IdentifyApplianceRoute
  '/step-2/model-details': typeof Step2ModelDetailsRoute
  '/step-3/safety-checklist': typeof Step3SafetyChecklistRoute
  '/step-4/preparation': typeof Step4PreparationRoute
  '/step-5/installation': typeof Step5InstallationRoute
  '/step-6/complete': typeof Step6CompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/step-1/identify-appliance': typeof Step1IdentifyApplianceRoute
  '/step-2/model-details': typeof Step2ModelDetailsRoute
  '/step-3/safety-checklist': typeof Step3SafetyChecklistRoute
  '/step-4/preparation': typeof Step4PreparationRoute
  '/step-5/installation': typeof Step5InstallationRoute
  '/step-6/complete': typeof Step6CompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/step-1/identify-appliance': typeof Step1IdentifyApplianceRoute
  '/step-2/model-details': typeof Step2ModelDetailsRoute
  '/step-3/safety-checklist': typeof Step3SafetyChecklistRoute
  '/step-4/preparation': typeof Step4PreparationRoute
  '/step-5/installation': typeof Step5InstallationRoute
  '/step-6/complete': typeof Step6CompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/step-1/identify-appliance'
    | '/step-2/model-details'
    | '/step-3/safety-checklist'
    | '/step-4/preparation'
    | '/step-5/installation'
    | '/step-6/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/step-1/identify-appliance'
    | '/step-2/model-details'
    | '/step-3/safety-checklist'
    | '/step-4/preparation'
    | '/step-5/installation'
    | '/step-6/complete'
  id:
    | '__root__'
    | '/'
    | '/step-1/identify-appliance'
    | '/step-2/model-details'
    | '/step-3/safety-checklist'
    | '/step-4/preparation'
    | '/step-5/installation'
    | '/step-6/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Step1IdentifyApplianceRoute: typeof Step1IdentifyApplianceRoute
  Step2ModelDetailsRoute: typeof Step2ModelDetailsRoute
  Step3SafetyChecklistRoute: typeof Step3SafetyChecklistRoute
  Step4PreparationRoute: typeof Step4PreparationRoute
  Step5InstallationRoute: typeof Step5InstallationRoute
  Step6CompleteRoute: typeof Step6CompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-6/complete': {
      id: '/step-6/complete'
      path: '/step-6/complete'
      fullPath: '/step-6/complete'
      preLoaderRoute: typeof Step6CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-5/installation': {
      id: '/step-5/installation'
      path: '/step-5/installation'
      fullPath: '/step-5/installation'
      preLoaderRoute: typeof Step5InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-4/preparation': {
      id: '/step-4/preparation'
      path: '/step-4/preparation'
      fullPath: '/step-4/preparation'
      preLoaderRoute: typeof Step4PreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-3/safety-checklist': {
      id: '/step-3/safety-checklist'
      path: '/step-3/safety-checklist'
      fullPath: '/step-3/safety-checklist'
      preLoaderRoute: typeof Step3SafetyChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-2/model-details': {
      id: '/step-2/model-details'
      path: '/step-2/model-details'
      fullPath: '/step-2/model-details'
      preLoaderRoute: typeof Step2ModelDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-1/identify-appliance': {
      id: '/step-1/identify-appliance'
      path: '/step-1/identify-appliance'
      fullPath: '/step-1/identify-appliance'
      preLoaderRoute: typeof Step1IdentifyApplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Step1IdentifyApplianceRoute: Step1IdentifyApplianceRoute,
  Step2ModelDetailsRoute: Step2ModelDetailsRoute,
  Step3SafetyChecklistRoute: Step3SafetyChecklistRoute,
  Step4PreparationRoute: Step4PreparationRoute,
  Step5InstallationRoute: Step5InstallationRoute,
  Step6CompleteRoute: Step6CompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
